# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokeMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokeMe
  pod 'SDWebImage'
  pod 'NVActivityIndicatorView', '4.8.0'
  target 'PokeMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokeMeUITests' do
    # Pods for testing
  end

end
